apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmit-store-server-pod
  labels:
    name: rmit-store-server-pod
    app: rmit-store-server
    version: stable
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3000"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rmit-store-server
      version: stable
  template:
    metadata:
      labels:
        app: rmit-store-server
        name: rmit-store-server-pod
        version: stable
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: rmit-store-server-pod
          image: locoioioi/be-mern-server:stable
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      nodeSelector:
        eks.amazonaws.com/nodegroup: server-worker-group
---
apiVersion: v1
kind: Service
metadata:
  name: rmit-store-server-service
  labels:
    name: rmit-store-server-service
    app: rmit-store
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: rmit-store-server
