apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9216"
spec:
  type: NodePort
  selector:
    app: mongodb-exporter
  ports:
    - protocol: TCP
      port: 9216
      targetPort: 9216
      nodePort: 30092
