name: Jenkins CI PR FE

on:
  pull_request:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  build-push-trigger:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker E2E Testing Image
      - name: Build Docker E2E Testing image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/e2e:latest -f ./client/Dockerfile.e2e ./client

      - name: Push Docker E2E Testing image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/e2e:latest

      # Step 4: Trigger Jenkins Job (Using Secret for Jenkins IP)
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://${{ secrets.JENKINS_IP }}:8080/job/fe-ci/buildWithParameters?branch=${{ github.head_ref }}" \
            --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }} \
            --header "Content-Type: application/json"

      - name: Install jq
        run: sudo apt-get install jq

      # Step 5: Wait for Jenkins Job to Complete (Using Secret for Jenkins IP)
      - name: Wait for Jenkins Job
        id: wait_jenkins
        run: |
          JENKINS_URL="http://${{ secrets.JENKINS_IP }}:8080"
          JOB_NAME="fe-ci"
          USER="${{ secrets.JENKINS_USER }}"
          API_TOKEN="${{ secrets.JENKINS_API_TOKEN }}"
          BUILD_URL="$JENKINS_URL/job/$JOB_NAME/lastBuild/api/json"
          STATUS="IN_PROGRESS"

          while [ "$STATUS" != "SUCCESS" ] && [ "$STATUS" != "FAILURE" ]; do
            echo "Checking Jenkins job status..."
            sleep 10
            STATUS=$(curl -s --user $USER:$API_TOKEN $BUILD_URL | jq -r '.result')
            echo "Current status: $STATUS"
          done

          if [ "$STATUS" == "SUCCESS" ]; then
            echo "Jenkins job completed successfully!"
          else
            echo "Jenkins job failed. Exiting with error."
            exit 1
          fi
