name: Jenkins CI PR BE

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'server/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'